mysql_db.js

added a heartbeat for when mysql is inactive

---

cassandra_db.js
defaultTestSettings.js
package.json

This replaces the old Helenus driver and uses the now "official" nodejs driver to talk to Cassandra.
This is not CQL3 compatible just yet. I'd like to submit a separate PR for that body of work (or update the existing PR)

Brought in the new Cassandra driver

---

README.md
defaultTestSettings.js
elasticsearch_db.js
package.json

Implementation for using Elasticsearch with UeberDB.
Findkeys functionality only works for the *:*:* pattern.

Elasticsearch

---

couch_db.js

Hi again,
So I've repaired my mistakes (I think).
Still without `felix-couchdb` being updated, this won't work anyway :(
I was wandering if it's possible to switch to [nano](https://github.com/dscape/nano) which seems to be more actively maintained?

COUCHED - add findkey method

---

couch_db.js

My bad… I've clean too much the code :disappointed: 
Still I haven't this error in `benchmark.js` but only while using it with etherpad :S

FIX - couch default settings

---

README.md

Last PR I hope :smile: 
Hope you can push it on NPM soon!

README - fix couch doc

---

mysql_db.js

Default charset should be utf8mb4

Create mysql table with utf8mb4 charset

---

package.json

Update version to 0.3.6 before releasing new version to npmjs.com

---

README.md

Added some documentation to explain what is mentioned in this [issue](https://github.com/ether/etherpad-lite/issues/4044)
Feel free to adapt it, I don't know how you want to organize your documentation.

update README to explain Redis TLS support

---

databases/postgres_common.js

This is a somewhat ugly solution, but a quick fix is better than broken
installations …
Hopefully fixes the issue mentioned in #133 and ether/etherpad-lite#4271.

postgres: Fix upsert via function when using jsonb data type

---

databases/postgres_common.js

Two commits:
* PostgreSQL: Fix lack of error handling
* PostgreSQL: Fix bad callback value
Fixes #139.

PostgreSQL: Fix initialization error handling and callback

---

.gitignore
databases/elasticsearch_db.js
databases/postgres_common.js
databases/redis_db.js
package-lock.json
test/test.js

This PR contains non-lint fixes from #143:
* Don't call undefined functions
* Fix use of undefined variable
* Use `fs.stat` to check existence, not deprecated `fs.exists`
* use create if not exists
* Commit `package-lock.json`

Various fixes

---

README.md
package-lock.json
package.json
test/lib/databases.js

* sqlite: Add optional dependency on `sqlite3`
* Add sqlite to tests
* README.md: Add SQLite

Support SQLite

---

.github/workflows/npmpublish.yml
.gitignore
.travis.yml
databases/mongodb_db.js
package-lock.json
package.json
test/lib/databases.js

Hello,
This PR add the mongodb support for ueberDB

Add mongodb support

---

test/test.js

* tests: Log total ms and total ms per count
* tests: Use convenience `set`, `get` functions
* tests: Move convenience functions to top `describe`
* tests: Fix disabling of read cache

Various test fixes

---

package-lock.json
package.json

Updating mssql dep as per https://github.com/tediousjs/node-mssql/issues/1150
Weirdly when I was doing this sqlite kept being added as dep, I had to manually remove it.  Hopefully this wont cause any pain.

Bump mssql to 7.0.0 alpha.

---

test/lib/databases.js
test/test.js

* tests: Typo fix: `findKey` -> `findKeys`
* tests: Avoid `util.promisify` overhead
* tests: Increase `mysql`'s acceptable `get()` time
* tests: Wait for writes to complete during speed tests
* tests: Only check acceptable speeds if read cache is enabled
* tests: Also test with write buffering disabled
I recommend ignoring white space changes when reviewing the last of these commits.

Various test fixes and improvements

---

test/test.js

Also make sure that everything can take a 100 character long key.

tests: Make sure test keys satisfy the 100 character limit

---

lib/CacheAndBufferLayer.js
test/test_lru.js

* cache: Use a LRU structure to improve eviction performance
* cache: Don't evict old entries after writes complete

cache: Use a LRU structure to improve eviction performance

---

package-lock.json
package.json

* Update dependencies again
* Delete unused dependencies from `package.json`
* Move test-only dependencies to `devDependencies`

Dependency fixes

---

README.md

but i lack of data for "Feature support" part :\

reintroduce mongodb support in readme

---

databases/dirty_db.js
index.js
lib/CacheAndBufferLayer.js
test/lib/databases.js

* Set DB to null on `close()`
* Use a variable to save some keystrokes
* cache: Promisify `close()`
* cache: Promisify `init()`
* cache: Promisify `get()`
* cache: Promisify `getSub()`
* cache: Promisify `findKeys()`
* tests: Increase `setMax` for `postgres`

cache: Promisify part 3: Read methods

---

databases/mock_db.js
index.js
lib/CacheAndBufferLayer.js
package-lock.json
package.json
test/test_metrics.js

This PR is marked as draft because it depends on PR #194. Once that PR is merged this can be rebased and marked as ready for review.

Add read, write, and lock metrics

---

CHANGELOG.md
lib/CacheAndBufferLayer.js
test/test_metrics.js

* cache: Handle JSON stringify errors
* tests: Refine cache metric tests
* cache: Refine metrics

cache: Refine metrics

---

databases/mysql_db.js

* mysql: Fix iteration over operations in `doBulk()`
* mysql: Promisify
* mysql: Let the `mysql` package build the SQL strings
The last of the commits might improve performance; we need better benchmarking to be sure.
FYI @packardone

mysql: Modernize, simplify, clean up

---

CHANGELOG.md
databases/mysql_db.js
test/test_mysql.js

mysql: Use a connection pool

---

CHANGELOG.md
databases/mongodb_db.js
test/lib/databases.js

* mongodb: Rename `dbName` setting to `database`
* mongodb: Make `database` optional
Fixes #185 
Addresses ether/etherpad-lite#5118
cc @Loki-Afro

mongodb: Config improvements

---

package-lock.json
package.json

sqlite3 is fetched from GitHub because the maintainers haven't yet published a node-gyp update to npm: https://github.com/mapbox/node-sqlite3/issues/1493

Update database drivers

---

CHANGELOG.md
databases/couch_db.js
test/lib/databases.js
test/test.js

couch: Fix `nano` v9.x config

---

package-lock.json

Bumping from lockfile v1 to v3 makes me really nervous.  It's fully test covered but I'm worried it will break something in Etherpad.

deps: more dep updates.

---

databases/mysql_db.ts
rollup.config.cjs.js

Fixed mysql bug with other charset than default.
