ether/ueberDB

- CloneAndAtomicLayer.js
- tests/CloneAndAtomicLayer.js
Etherpad does not provide a callback when calling ueberdb "remove" operation,
so we need to handle this scenario on our side.
Fix #92
> [fix] Do not raise error if no callback is provided on "remove" operation

- CacheAndBufferLayer.js
**NOTE:** It's partially reverting @JohnMcLear  -s commit https://github.com/Pita/ueberDB/commit/86ced9b3999ca6e46ec73bb93f6d9b1ec730d1b0 and it means it **MAY break the crate_db removal functionality**. We @JohnMcLear input on this one.
Had no better idea how to fix this tho, see details on the symptoms - https://github.com/Pita/ueberDB/issues/105
> Fix remove(key) not removing from storage - https://github.com/Pita/ueberDB/issues/105

- postgres_db.js
Cache setting should be under the control of client using ueberdb
> Allow option for setting cache limit

- mongodb_db.js
- package.json
- tests/mongodb_db.js
Main goal: allow connecting to mongodb using SSL (the old connector
didn't allow this kind of thing).
Other features:
- folder for automated tests;
- load of certificate file content into connetion setting (for mongo
only);
Note: we tried to upgrade node-mongodb driver, but the new version (2.2)
was failing on a lot of benchmark tests, while the current version (2.0)
was stable and didn't have any failure during some runnings of benchmark
scripts. The new version uses a much simpler structure of the
settings.extra, so it would be great if we could upgrade it. To make
this change easier, the code (and tests) are ready for both versions, so
whenever v.2.2 is stable we might change it here just by removing some
lines of code.
> [feat] Re-write mongodb connector to allow more flexible configs

- CacheAndBufferLayer.js
During research on https://github.com/ether/etherpad-lite/issues/2522 I came across this one.
```
[2015-03-13 21:28:50.106] [ERROR] console - ReferenceError: callback is not defined
at /home/etherpad-lite-tests/ethercleanclean/src/node_modules/ueberDB/CacheAndBufferLayer.js:334:8
at /home/etherpad-lite-tests/ethercleanclean/src/node_modules/ueberDB/node_modules/async/lib/async.js:436:21
at /home/etherpad-lite-tests/ethercleanclean/src/node_modules/ueberDB/CacheAndBufferLayer.js:170:11
at Query._callback (/home/etherpad-lite-tests/ethercleanclean/src/node_modules/ueberDB/mysql_db.js:115:5)
at Query.Sequence.end (/home/etherpad-lite-tests/ethercleanclean/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
at Query._handleFinalResultPacket …
```
> actually use the callbacks in setSub

- README.md
- elasticsearch_db.js
- package.json
* Version 2.6.1 of mysql library is from 2015, and has a Remote Memory Exposure vulnerability (see ether/etherpad-lite#3397).
This change updates the library at its latest version as of today (2.15.0).
Tested against mysql 5.7 with no evident regressions.
Since mysql 8 is not supported yet, let's document it in the README
* The Elasticsearch library depends on an old version of lodash, which causes a *Prototype Pollution* warning in `npm audit` which requires manual intervention.
* let's bump the version to **0.3.9**. This would include these change, plus the security fix merged with #112
> Security updates for mysql and elasticsearch + bump to 0.3.9

- postgres_db.js
Currently, when running on Postgres, UeberDB emulates UPSERTS operations on the key/value store via a pgsl function.
In 2016, with version 9.5, **[PostgreSQL](https://en.wikipedia.org/wiki/PostgreSQL#Release_history)** gained the ability of natively performing UPSERTS on tables, via the SQL construct [```ON CONFLICT ... DO UPDATE```](https://www.postgresql.org/docs/9.5/static/sql-insert.html#SQL-ON-CONFLICT).
**[CockroachDB](https://www.cockroachlabs.com/)**, being externally modeled after PostgreSQL, also [offers the same syntax](https://www.cockroachlabs.com/docs/stable/upsert.html#how-upsert-transforms-into-insert-on-conflict).
As of version 1.x, CockroachDB does _not_ support user defined functions.
This patch series aims to remove the use of the custom sql function …
> Support native UPSERTs & CrockroachDB

- mysql_db.js
The equality/`=` search breaks the prefix/`LIKE` search
Note that the `BINARY` was not necessary to fix the trailing whitespace issue observed in ether/etherpad-lite#2877, as `LIKE` is not subject to the `PAD SPACE` behaviour in MySQL, see https://dev.mysql.com/doc/refman/5.6/en/char.html (search for `PAD SPACE`).
It furthermore seems to be good practice to keep the `BINARY` to force a case-sensitive comparison, as `LIKE` doesn't seem to have guarantees regarding case-sensitivity. As the key is a column with a binary collation `LIKE` searches are forced to be case-sensitive though, see https://dev.mysql.com/doc/refman/5.6/en/case-sensitivity.html, so no need to force `BINARY` here as long as the `key` column keeps a case-sensitive collation.
This search is also not affected by the speed …
> Revert to pre- e8b58d0 state, fixes key search regression

- mysql_db.js
A recent change (df20d21a71cf) made the deletion core correct when db keys are utf8 characters, but introduced a performance regression.
That performance regression was (more or less) fixed in 7762f0096458, but that commit forgot to include the required change on bulkDelete(), too.
This change fixes that.
> Fix slow doBulk()

- databases/postgres_common.js
- databases/postgres_db.js
- databases/postgrespool_db.js
This is supported since Postgres 9.2.  At the moment, Debian oldstable (jessie)
ships 9.6, and CentOS 6 – which is supported until November this year –
8.something.  I doubt anyone will really run anything older than this, and not
supporting CentOS 6 seems okay to me.
The init function will automatically check the data type of the value column and
migrate if it’s still text.
I hope the code is sensible, this is my first time writing JavaScript …
> postgres: Use Postgres’ jsonb data type for efficience

- .github/workflows/npmpublish.yml
- package.json
It is already an optional dependency, and should stay that way due to the need to compile C code (on some platforms).
> Remove sqlite3 from dependencies

- README.md
- databases/cassandra_db.js
- databases/couch_db.js
- databases/dirty_db.js
- databases/dirty_git_db.js
- databases/elasticsearch_db.js
- databases/mongodb_db.js
- databases/mssql_db.js
- databases/mysql_db.js
- databases/postgres_common.js
- databases/postgres_db.js
- databases/postgrespool_db.js
- databases/redis_db.js
- databases/rethink_db.js
- databases/sqlite_db.js
- index.js
- lib/CacheAndBufferLayer.js
- package-lock.json
- package.json
- test/test.js
There should be no behavior change with this PR.
* Use `this` instead of `self`, `_this`, or `that`
* cache: Simplify write callback conditional
* cache: Avoid iterating over inherited properties
* cache: Avoid repeated key lookups
* cache: Invert the dirty check (for readability)
* cache: Simplify `gc()` delete loop
* Rename `database` constructors to `Database`
* cassandra: Use template literal instead of `util.format()`
> Various cleanups

- lib/CacheAndBufferLayer.js
* cache: Convert `flush()` function to a method
* cache: Fix off-by-one bug in `gc()`
* cache: Run `gc()` even if read cache is disabled
* cache: Fix overly aggressive cache entry deletion in `gc()`
* cache: Simplify cache check in `get()`
* cache: Return from `get()` early if there is a cache entry
> Minor cache fixes and cleanups

- README.md
Setting `db.cache` to 0 has no effect on caching.
> Fix documentation describing how to disable caching

- lib/CacheAndBufferLayer.js
* cache: Call `bufferCallback` asynchronously
* cache: Don't compare with true or false, just use truthiness
* cache: Always call the callback passed to `flush()`
> More minor cache fixes and cleanups

- lib/CacheAndBufferLayer.js
* Always stage writes in `this.buffer` even if write buffering is disabled. This ensures that a call to `get()` always sees the most recently set value.
* Factor out write logic that is identical in `set()` and `flush()`.
* Avoid an unnecessary write when the new value is already in the database.
> cache: Redo write logic to fix a corner case

- package.json
This ensures that `npm up` will upgrade to 7.0.0 once it is released. (The API is unlikely to change before then so this is OK.)
> mssql: Use a semver range for the mssql dependency

- CHANGELOG.md
- index.js
- lib/CacheAndBufferLayer.js
- package-lock.json
- package.json
- test/test.js
* Add `CHANGELOG.md`
* cache: Return early if there is an error
* cache: Call `flush()` callback asynchronously
* cache: Recursively call `flush()` to drain all dirty entries
* cache: Only call `flush()` callback after flushing is done
* cache: Stop periodic flushes in `close()`, not `doShutdown()`
* cache: Flush entries before closing the db
* cache: Flush immediately upon `doShutdown()`
* cache: Re-think how the write callbacks are called
* New `flush()` method
* Deprecate `doShutdown()` in favor of `flush()`
Fixes #74.
> Flush improvements

- lib/CacheAndBufferLayer.js
- test/test.js
* tests: Drop "Acceptable ms/op" column if there is no enforced limit
* tests: Move db promisification to a separate function
* tests: Factor out common promisification logic
* tests: Fix error handling in `promisifyBufferedFn()`
* tests: Add tests for `getSub()`, `setSub()`
* cache: Always call both of the callbacks (buffered and written)
* cache: Fix `setSub()` corner cases
None of the issues fixed in this PR are new, so this is unlikely to address #176 or ether/etherpad-lite#4645.
> cache: Fix `setSub()` corner cases

- lib/CacheAndBufferLayer.js
* cache: Always call the callback passed to `get()` asynchronously
* cache: Always mark the cache entry as most recently used in `set()`
* cache: Always assume that `set()` is called with a new value
Fixes #176.
> Fix setSub() failure to update records

- databases/redis_db.js
* redis: Add missing `return` in `auth()`
* redis: Invert condition in `auth()` and `select()` for readability
This should fix the exception that was reported in ether/etherpad-lite#4693.
> redis: Fix "Callback was already called" error

- databases/redis_db.js
As per discussion in https://github.com/ether/etherpad-lite/issues/4693
> Pass object to redis createClient

- databases/dirty_db.js
Addresses but is not a proper fix for https://github.com/ether/etherpad-lite/issues/4684.
> dirty: Work around write-after-close bug in `dirty` package

- index.js
- lib/CacheAndBufferLayer.js
First in a series to modernize ueberDB:
* cache: Asyncify `_write()`
* cache: Asyncify `flush()`
> cache: Asyncify part 1

- lib/CacheAndBufferLayer.js
* cache: Add a comment explaining why `set()` always marks dirty
* cache: Delete unnecessary `if` condition
* cache: Set `entry.dirty = false` after write (for readability)
* cache: Document the properties of a cache entry
* cache: Use a Promise instead of a list of callbacks
> cache: Asyncify part 2: Use a Promise to manage write callbacks

- CHANGELOG.md
- databases/redis_db.js
- package-lock.json
- package.json
- test/lib/databases.js
* docs: Update `CHANGELOG.md`
* redis: Don't call `auth()` or `select()` with new config object
* redis tests: Delete ignored `hostname` setting
* Bump minor version for `redis` API change
> redis: Fix initialization with new settings object

- index.js
- lib/CacheAndBufferLayer.js
- package-lock.json
- package.json
* Remove useless locking around `findKeys()`
* Move locking into cache, convert to Promises
* Expose a metric for lock contention
This is marked as draft because it depends on PR #193. Once that PR is merged this can be rebased and marked as ready for review.
> cache: Promisify part 4: Modernize locking

- CHANGELOG.md
- README.md
- databases/mock_db.js
- index.js
- lib/CacheAndBufferLayer.js
- package-lock.json
- package.json
- test/test.js
- test/test_metrics.js
* cache: Deprecate `bufferCallback` argument
* cache: Promisify `set()`
* cache: Promisify `remove()`
* cache: Promisify `setSub()`
* cache: Avoid calling `util.promisify()` again and again
* cache: Let db drivers declare that they provide async methods
This is marked as draft because it depends on PR #195. Once that PR is merged this can be rebased and marked as ready for review.
> cache: Promisify part 5: Write methods

- CHANGELOG.md
- databases/mysql_db.js
- lib/CacheAndBufferLayer.js
- test/test_bulk.js
Limit bulk writes to 100 operations at a time to avoid timeouts. With the bulk write limit in place it should be safe to increase the cache size so remove the cache size override.
FYI @packardone
> mysql: Limit bulk query size, increase cache size

- CHANGELOG.md
- databases/mysql_db.js
- test/test_mysql.js
* mysql: Promisify `close()`
* mysql: Use ES6 class syntax for readability
* mysql: Avoid adding properties to the connection object
* mysql: Reconnect on fatal error
* mysql: Add ability to set logger object
* mysql: Log MySQL errors
* mysql: Pass query values via options object
* mysql: Move timeout into `_query()`
* mysql: Separate MySQL settings from ueberdb settings
* mysql: Move default query timeout to settings
* mysql: Reschedule ping after each connect and query
cc @packardone
> mysql: Reconnect on fatal error and other improvements

- CHANGELOG.md
- databases/mock_db.js
- index.js
- lib/CacheAndBufferLayer.js
- test/test_bulk.js
- test/test_metrics.js
* cache: Use the logger object when logging errors
* mock: Decrease `writeInterval` to speed up tests
* tests: Redo write metric tests for readability, flexibility
* cache: Also increment write metrics if `setSub()` read fails
* cache: Retry bulk write operations individually
cc @packardone
> cache: If bulk write fails, retry each write individually

- README.md
- databases/cassandra_db.js
- databases/couch_db.js
- databases/dirty_db.js
- databases/dirty_git_db.js
- databases/elasticsearch_db.js
- databases/mongodb_db.js
- databases/mssql_db.js
- databases/mysql_db.js
- databases/postgres_common.js
- databases/postgres_db.js
- databases/postgrespool_db.js
- databases/redis_db.js
- databases/rethink_db.js
- databases/sqlite_db.js
- index.js
- lib/AbstractDatabase.js
- lib/CacheAndBufferLayer.js
* Use ES6 class syntax for readability
* Derive all database classes from a new AbstractDatabase class
* Move `createFindRegex` to AbstractDatabase
> Use ES6 class hierarchy for database classes

- databases/sqlite_db.js
In theory we could use --no-save, but then after ./bin/run.sh the dependency would be gone again.
> npm i sqlite3 should be run in ./src

- index.ts
It seems that in the process of refactoring from .js to .ts a bug got created which breaks the deprecated usage of the `set` function. This PR is fixing this problem. 
Its just three letters which got wrong.  `cbDb.get.call` which needed to be `cbDb.set.call` :  https://github.com/ether/ueberDB/blob/main/index.ts#L223 
This creates a misfunction way ahead in some third party etherpad plugin usage (in this case framasoft/ep_mypads ) with the current release of etherpad (1.9.3). 
While etherpad 1.9.1 still uses ueberDB2 (v4.0.11) it works still fine. This was before the refactoring to typescript and in this case the `set` function was still using `cbDb.set.call` as it can be seen here: https://github.com/ether/ueberDB/blob/6919908c289cff4101b4e65fdc0b72c3f95f3605/index.js#L132
would be …
> fixing `set` function bug for deprecated use
